### ISSUE TITLE
a crash in scaleText

### ISSUE THREAD

**Issue by chenyusheng** [hanks-zyh/HTextView#64]
this is the detail message:
#3485 java.lang.NullPointerException
Attempt to invoke virtual method 'float android.text.Layout.getLineLeft(int)' on a null object reference
com.hanks.htextview.base.HText$1.onGlobalLayout(HText.java:55)

how can i fix this crash？

**Comment by SirWellington** [comment]
This happened to me because I was calling `animateText()` before the view was laid out.
To fix, basically do:

```kotlin
with(textView) {
                    post {
                        animateText("Date Deanna for $1.99")
                    }
}
```

**Comment by chenyusheng** [comment]
it help me to solve this question! thank you

**Comment by vedantkarandikar** [comment]
The actual solution would be to check all Animation Handlers and Libraries, especially if you are using the default  ` android:animateLayoutChanges="true"`. This causes Android to take control of animateText or SetVisiblity(), but because animateText is already animating on its own, one of them get the NPE. Remove `android:animateLayoutChanges="true"` or reconfigure the delay in animations. Also add buffer, as postDelay isn't perfect.
